#!/bin/sh
case "$1" in
        c*) sudo sh capture.sh ;;
        p*) python3 plot.py *.json ;;
        *) echo "MacPlot by chrissx <chrissx@chrissx.de>
Usage:
./macplot capture: capture data
./macplot plot: plot a graph" ;;
esac
